version: '3.7'

services:
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops_app
    ports:
      - "8000:8000"
    environment:
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - app_network

  clearml-agent:
    image: allegroai/clearml-agent:latest
    environment:
      CLEARML_AGENT_WORKER_NAME: "worker_1"
      CLEARML_API_ACCESS_KEY: "QA82E184K40OMKN60B5TF0964UPFPU"
      CLEARML_API_SECRET_KEY: "YpF78YHhfCfZFq_RM-LlIky_eXgiJgJBWqocAcqYiNM3zOcbArnerQGagBhDdvhnJSI"
      CLEARML_API_SERVER: "https://app.clear.ml"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.clearml:/root/.clearml

  clearml-server:
    image: allegroai/clearml:latest
    ports:
      - "8080:8080" 
      - "8081:8081"
      - "8082:8082"
    environment:
      CLEARML_APPLY_MONGO_PATCH: "true"
    volumes:
      - clearml_data:/opt/clearml/data
      - clearml_logs:/opt/clearml/logs


volumes:
  minio-storage:
  postgres_data:
  clearml_data:
  clearml_logs:

networks:
  app_network:
    driver: bridge