# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_app/message_interface.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'grpc_app/message_interface.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n grpc_app/message_interface.proto\"\xeb\x01\n\x0cTrainRequest\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12;\n\x0fhyperparameters\x18\x02 \x03(\x0b\x32\".TrainRequest.HyperparametersEntry\x12%\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x17.TrainRequest.DataEntry\x1a\x36\n\x14HyperparametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"!\n\rTrainResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\"0\n\x0ePredictRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"&\n\x0fPredictResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\x02\"!\n\rDeleteRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x99\x01\n\x0cModelService\x12+\n\nTrainModel\x12\r.TrainRequest\x1a\x0e.TrainResponse\x12,\n\x07Predict\x12\x0f.PredictRequest\x1a\x10.PredictResponse\x12.\n\x0b\x44\x65leteModel\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_app.message_interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._loaded_options = None
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_TRAINREQUEST_DATAENTRY']._loaded_options = None
  _globals['_TRAINREQUEST_DATAENTRY']._serialized_options = b'8\001'
  _globals['_TRAINREQUEST']._serialized_start=37
  _globals['_TRAINREQUEST']._serialized_end=272
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._serialized_start=173
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._serialized_end=227
  _globals['_TRAINREQUEST_DATAENTRY']._serialized_start=229
  _globals['_TRAINREQUEST_DATAENTRY']._serialized_end=272
  _globals['_TRAINRESPONSE']._serialized_start=274
  _globals['_TRAINRESPONSE']._serialized_end=307
  _globals['_PREDICTREQUEST']._serialized_start=309
  _globals['_PREDICTREQUEST']._serialized_end=357
  _globals['_PREDICTRESPONSE']._serialized_start=359
  _globals['_PREDICTRESPONSE']._serialized_end=397
  _globals['_DELETEREQUEST']._serialized_start=399
  _globals['_DELETEREQUEST']._serialized_end=432
  _globals['_DELETERESPONSE']._serialized_start=434
  _globals['_DELETERESPONSE']._serialized_end=467
  _globals['_MODELSERVICE']._serialized_start=470
  _globals['_MODELSERVICE']._serialized_end=623
# @@protoc_insertion_point(module_scope)
